name: CI Docker 

on:
 workflow_dispatch:


jobs:
 ci_build_containerization:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v6.0.2
   - name: Docker Login 
     uses: docker/login-action@v3.6.0
     with:
      username: ${{vars.DOCKER_UN}}
      password: ${{secrets.DOCKER_PSWD_NEW}}
   -  name: Docker Setup Buildx 
      run: |
       docker build -t ${{vars.DOCKER_UN}}/my_python_app:latest . 

   -  name: Docker Push
      run: |
       docker push ${{vars.DOCKER_UN}}/my_python_app:latest
      
      
